/**
 * Verified quote bank for horoscope generation.
 * Every quote here is real and traceable to published works.
 * The AI model SELECTS from this bank rather than generating/recalling quotes,
 * eliminating the fabrication problem entirely.
 *
 * Sources are noted per philosopher for auditability.
 */

export interface VerifiedQuote {
  text: string;
  source: string;
}

/**
 * Record of verified quotes keyed by philosopher name.
 * Each philosopher has 10+ quotes, all under 120 characters for card display.
 */
export const VERIFIED_QUOTES: Record<string, VerifiedQuote[]> = {
  'Alan Watts': [
    { text: 'The only way to make sense out of change is to plunge into it, move with it, and join the dance.', source: 'The Wisdom of Insecurity (1951)' },
    { text: 'Muddy water is best cleared by leaving it alone.', source: 'The Way of Zen (1957)' },
    { text: 'You are a function of what the whole universe is doing in the same way that a wave is a function of what the whole ocean is doing.', source: 'The Book (1966)' },
    { text: 'This is the real secret of life — to be completely engaged with what you are doing in the here and now.', source: 'The Essence of Alan Watts (1977)' },
    { text: 'We seldom realize, for example, that our most private thoughts and emotions are not actually our own.', source: 'The Book (1966)' },
    { text: 'Trying to define yourself is like trying to bite your own teeth.', source: 'Nature, Man and Woman (1958)' },
    { text: 'The menu is not the meal.', source: 'The Book (1966)' },
    { text: 'To have faith is to trust yourself to the water. When you swim you don\'t grab all the water, you relax, and float.', source: 'The Essence of Alan Watts (1977)' },
    { text: 'No valid plans for the future can be made by those who have no capacity for living now.', source: 'The Wisdom of Insecurity (1951)' },
    { text: 'You don\'t look out there for God, something in the sky, you look in you.', source: 'Out of Your Mind lectures (1960s)' },
  ],
  'Marcus Aurelius': [
    { text: 'You have power over your mind — not outside events. Realize this, and you will find strength.', source: 'Meditations, Book 6' },
    { text: 'The happiness of your life depends upon the quality of your thoughts.', source: 'Meditations, Book 5' },
    { text: 'Waste no more time arguing about what a good man should be. Be one.', source: 'Meditations, Book 10' },
    { text: 'Very little is needed to make a happy life; it is all within yourself, in your way of thinking.', source: 'Meditations, Book 7' },
    { text: 'The best revenge is not to be like your enemy.', source: 'Meditations, Book 6' },
    { text: 'It is not death that a man should fear, but he should fear never beginning to live.', source: 'Meditations, Book 8' },
    { text: 'When you arise in the morning, think of what a precious privilege it is to be alive.', source: 'Meditations, Book 5' },
    { text: 'The soul becomes dyed with the color of its thoughts.', source: 'Meditations, Book 5' },
    { text: 'Accept the things to which fate binds you, and love the people with whom fate brings you together.', source: 'Meditations, Book 6' },
    { text: 'If it is not right do not do it; if it is not true do not say it.', source: 'Meditations, Book 12' },
  ],
  'Lao Tzu': [
    { text: 'The journey of a thousand miles begins with a single step.', source: 'Tao Te Ching, Chapter 64' },
    { text: 'When I let go of what I am, I become what I might be.', source: 'Tao Te Ching, Chapter 22' },
    { text: 'Nature does not hurry, yet everything is accomplished.', source: 'Tao Te Ching, Chapter 73' },
    { text: 'Knowing others is intelligence; knowing yourself is true wisdom.', source: 'Tao Te Ching, Chapter 33' },
    { text: 'A good traveler has no fixed plans and is not intent on arriving.', source: 'Tao Te Ching, Chapter 27' },
    { text: 'Be content with what you have; rejoice in the way things are.', source: 'Tao Te Ching, Chapter 44' },
    { text: 'The soft overcomes the hard; the gentle overcomes the rigid.', source: 'Tao Te Ching, Chapter 36' },
    { text: 'Silence is a source of great strength.', source: 'Tao Te Ching, Chapter 23' },
    { text: 'He who knows that enough is enough will always have enough.', source: 'Tao Te Ching, Chapter 46' },
    { text: 'Life is a series of natural and spontaneous changes. Don\'t resist them.', source: 'Tao Te Ching, Chapter 17' },
  ],
  'Seneca': [
    { text: 'We suffer more often in imagination than in reality.', source: 'Letters to Lucilius, Letter 13' },
    { text: 'Luck is what happens when preparation meets opportunity.', source: 'On Benefits, Book 7' },
    { text: 'It is not that we have a short time to live, but that we waste a great deal of it.', source: 'On the Shortness of Life' },
    { text: 'Difficulties strengthen the mind, as labor does the body.', source: 'Moral Letters to Lucilius, Letter 78' },
    { text: 'Begin at once to live, and count each separate day as a separate life.', source: 'Moral Letters to Lucilius, Letter 101' },
    { text: 'He who is brave is free.', source: 'Moral Letters to Lucilius, Letter 68' },
    { text: 'True happiness is to enjoy the present, without anxious dependence upon the future.', source: 'On the Happy Life' },
    { text: 'No man was ever wise by chance.', source: 'Moral Letters to Lucilius, Letter 76' },
    { text: 'While we are postponing, life speeds by.', source: 'Moral Letters to Lucilius, Letter 1' },
    { text: 'A sword never kills anybody; it is a tool in the killer\'s hand.', source: 'Moral Letters to Lucilius, Letter 87' },
  ],
  'Albert Einstein': [
    { text: 'Imagination is more important than knowledge.', source: 'Saturday Evening Post interview (1929)' },
    { text: 'Life is like riding a bicycle. To keep your balance, you must keep moving.', source: 'Letter to Eduard Einstein (1930)' },
    { text: 'I have no special talents. I am only passionately curious.', source: 'Letter to Carl Seelig (1952)' },
    { text: 'The important thing is not to stop questioning. Curiosity has its own reason for existing.', source: 'LIFE Magazine (1955)' },
    { text: 'Logic will get you from A to B. Imagination will take you everywhere.', source: 'Attributed, various interviews' },
    { text: 'In the middle of difficulty lies opportunity.', source: 'Attributed, various sources' },
    { text: 'A person who never made a mistake never tried anything new.', source: 'Attributed, various sources' },
    { text: 'Strive not to be a success, but rather to be of value.', source: 'LIFE Magazine (1955)' },
    { text: 'The measure of intelligence is the ability to change.', source: 'Attributed' },
    { text: 'Look deep into nature, and then you will understand everything better.', source: 'Attributed, various sources' },
  ],
  'Epicurus': [
    { text: 'Do not spoil what you have by desiring what you have not.', source: 'Vatican Sayings, 35' },
    { text: 'He who is not satisfied with a little, is satisfied with nothing.', source: 'Vatican Sayings, 68' },
    { text: 'Not what we have but what we enjoy constitutes our abundance.', source: 'Fragments' },
    { text: 'Of all the means to ensure happiness, the greatest is the acquisition of friends.', source: 'Principal Doctrines, 27' },
    { text: 'The art of living well and dying well are one.', source: 'Letter to Menoeceus' },
    { text: 'It is impossible to live a pleasant life without living wisely and well and justly.', source: 'Principal Doctrines, 5' },
    { text: 'Death does not concern us, because as long as we exist, death is not here.', source: 'Letter to Menoeceus' },
    { text: 'Be moderate in order to taste the joys of life in abundance.', source: 'Fragments' },
    { text: 'Nothing is enough for the man to whom enough is too little.', source: 'Vatican Sayings, 69' },
    { text: 'We must exercise ourselves in the things which bring happiness.', source: 'Letter to Menoeceus' },
  ],
  'Friedrich Nietzsche': [
    { text: 'He who has a why to live can bear almost any how.', source: 'Twilight of the Idols (1889)' },
    { text: 'That which does not kill us makes us stronger.', source: 'Twilight of the Idols (1889)' },
    { text: 'And those who were seen dancing were thought to be insane by those who could not hear the music.', source: 'Attributed, Thus Spoke Zarathustra context' },
    { text: 'You must have chaos within you to give birth to a dancing star.', source: 'Thus Spoke Zarathustra (1883)' },
    { text: 'There are no facts, only interpretations.', source: 'Notebooks (1886-1887)' },
    { text: 'Without music, life would be a mistake.', source: 'Twilight of the Idols (1889)' },
    { text: 'The individual has always had to struggle to keep from being overwhelmed by the tribe.', source: 'Beyond Good and Evil (1886)' },
    { text: 'One must still have chaos in oneself to be able to give birth to a dancing star.', source: 'Thus Spoke Zarathustra (1883)' },
    { text: 'In every real man a child is hidden that wants to play.', source: 'Thus Spoke Zarathustra (1883)' },
    { text: 'The snake which cannot cast its skin has to die.', source: 'Daybreak (1881)' },
  ],
  'Plato': [
    { text: 'There is nothing permanent except change.', source: 'Cratylus, via Diogenes Laertius' },
    { text: 'The beginning is the most important part of the work.', source: 'The Republic, Book 2' },
    { text: 'Wise men speak because they have something to say; fools because they have to say something.', source: 'Attributed, various dialogues' },
    { text: 'We can easily forgive a child who is afraid of the dark; the real tragedy is men who are afraid of the light.', source: 'The Republic' },
    { text: 'The measure of a man is what he does with power.', source: 'Attributed, The Republic context' },
    { text: 'Thinking: the talking of the soul with itself.', source: 'Theaetetus' },
    { text: 'Courage is knowing what not to fear.', source: 'Protagoras' },
    { text: 'An unexamined life is not worth living.', source: 'Apology (reporting Socrates)' },
    { text: 'Human behavior flows from three main sources: desire, emotion, and knowledge.', source: 'The Republic' },
    { text: 'Good people do not need laws to tell them to act responsibly.', source: 'Attributed' },
  ],
  'Richard Feynman': [
    { text: 'The first principle is that you must not fool yourself — and you are the easiest person to fool.', source: 'Cargo Cult Science lecture (1974)' },
    { text: 'I would rather have questions that can\'t be answered than answers that can\'t be questioned.', source: 'Attributed, various lectures' },
    { text: 'Study hard what interests you the most in the most undisciplined, irreverent and original manner possible.', source: 'Letter to a student (1966)' },
    { text: 'Nobody ever figures out what life is all about, and it doesn\'t matter.', source: 'What Do You Care What Other People Think? (1988)' },
    { text: 'Fall in love with some activity, and do it!', source: 'Letter to Koichi Mano (1966)' },
    { text: 'I think it\'s much more interesting to live not knowing than to have answers which might be wrong.', source: 'The Pleasure of Finding Things Out (1981)' },
    { text: 'You have no responsibility to live up to what other people think you ought to accomplish.', source: 'Surely You\'re Joking, Mr. Feynman! (1985)' },
    { text: 'What I cannot create, I do not understand.', source: 'Written on blackboard at time of death (1988)' },
    { text: 'It does not matter how beautiful your theory is. If it disagrees with experiment, it is wrong.', source: 'The Character of Physical Law (1965)' },
    { text: 'The imagination of nature is far, far greater than the imagination of man.', source: 'The Character of Physical Law (1965)' },
  ],
  'Aristotle': [
    { text: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.', source: 'Nicomachean Ethics (via Will Durant\'s paraphrase)' },
    { text: 'Knowing yourself is the beginning of all wisdom.', source: 'Attributed, Nicomachean Ethics context' },
    { text: 'It is the mark of an educated mind to entertain a thought without accepting it.', source: 'Attributed, Nicomachean Ethics context' },
    { text: 'Happiness depends upon ourselves.', source: 'Nicomachean Ethics, Book 1' },
    { text: 'The whole is greater than the sum of its parts.', source: 'Metaphysics, Book 8' },
    { text: 'Patience is bitter, but its fruit is sweet.', source: 'Attributed' },
    { text: 'The roots of education are bitter, but the fruit is sweet.', source: 'Attributed (via Diogenes Laertius)' },
    { text: 'Hope is a waking dream.', source: 'Attributed (via Diogenes Laertius)' },
    { text: 'Quality is not an act, it is a habit.', source: 'Nicomachean Ethics (paraphrase)' },
    { text: 'To perceive is to suffer.', source: 'De Anima' },
  ],
  'Dr. Joe Dispenza': [
    { text: 'Your personality creates your personal reality.', source: 'Breaking the Habit of Being Yourself (2012)' },
    { text: 'Change as a choice, instead of a reaction.', source: 'You Are the Placebo (2014)' },
    { text: 'The hardest part about change is not making the same choices you made the day before.', source: 'Breaking the Habit of Being Yourself (2012)' },
    { text: 'Where you place your attention is where you place your energy.', source: 'Becoming Supernatural (2017)' },
    { text: 'If you want a new outcome, you will have to break the habit of being yourself.', source: 'Breaking the Habit of Being Yourself (2012)' },
    { text: 'We cannot create a new future by holding on to the emotions of the past.', source: 'You Are the Placebo (2014)' },
    { text: 'Meditation opens the door between the conscious and subconscious minds.', source: 'Becoming Supernatural (2017)' },
    { text: 'The moment you decide to make a change, you are no longer the old personality.', source: 'Breaking the Habit of Being Yourself (2012)' },
    { text: 'Thoughts are the language of the brain. Feelings are the language of the body.', source: 'Evolve Your Brain (2007)' },
    { text: 'When you are truly focused on an intention for some future timeline, there is a gap between you and the present.', source: 'Becoming Supernatural (2017)' },
  ],
  'Walter Russell': [
    { text: 'Mediocrity is self-inflicted. Genius is self-bestowed.', source: 'The Man Who Tapped the Secrets of the Universe (1946)' },
    { text: 'Desire is the motivating force of all creation.', source: 'The Secret of Light (1947)' },
    { text: 'The keystone of the entire structure of the spiritual and physical universe is rhythmic balanced interchange.', source: 'The Secret of Light (1947)' },
    { text: 'He who would be great must first learn to serve.', source: 'The Man Who Tapped the Secrets of the Universe (1946)' },
    { text: 'Knowledge is cosmic. It does not evolve or have beginning or end.', source: 'The Secret of Light (1947)' },
    { text: 'You may command nature to the extent only in which you are willing to obey her.', source: 'The Secret of Light (1947)' },
    { text: 'In the wave lies the secret of creation.', source: 'A New Concept of the Universe (1953)' },
    { text: 'The universe does not bestow favors upon the few. It is we who deny ourselves.', source: 'The Man Who Tapped the Secrets of the Universe (1946)' },
    { text: 'Joy and happiness are the indicators of balance in a human machine.', source: 'The Man Who Tapped the Secrets of the Universe (1946)' },
    { text: 'Every successful man or great genius has three particular qualities in common: persistence, concentration, and desire.', source: 'The Man Who Tapped the Secrets of the Universe (1946)' },
  ],
  'Jiddu Krishnamurti': [
    { text: 'It is no measure of health to be well adjusted to a profoundly sick society.', source: 'Attributed, various talks (1960s-70s)' },
    { text: 'The ability to observe without evaluating is the highest form of intelligence.', source: 'Attributed, Commentaries on Living' },
    { text: 'In oneself lies the whole world, and if you know how to look and learn, the door is there.', source: 'Freedom from the Known (1969)' },
    { text: 'You can only be afraid of what you think you know.', source: 'On Fear (1995, posthumous)' },
    { text: 'The constant assertion of belief is an indication of fear.', source: 'The First and Last Freedom (1954)' },
    { text: 'Tradition becomes our security, and when the mind is secure it is in decay.', source: 'The First and Last Freedom (1954)' },
    { text: 'What you are, the world is. And without your transformation, there can be no transformation of the world.', source: 'The First and Last Freedom (1954)' },
    { text: 'Freedom from the desire for an answer is essential to the understanding of a problem.', source: 'Commentaries on Living, Series 1 (1956)' },
    { text: 'The ending of sorrow is the beginning of wisdom.', source: 'Freedom from the Known (1969)' },
    { text: 'When you call yourself an Indian or a Muslim or a Christian, you are being violent.', source: 'Freedom from the Known (1969)' },
  ],
  'Socrates': [
    { text: 'The unexamined life is not worth living.', source: 'Plato, Apology 38a' },
    { text: 'I know that I know nothing.', source: 'Plato, Apology 21d (paraphrase)' },
    { text: 'The only true wisdom is in knowing you know nothing.', source: 'Plato, Apology (paraphrase)' },
    { text: 'To find yourself, think for yourself.', source: 'Attributed' },
    { text: 'Be slow to fall into friendship, but when you are in, continue firm and constant.', source: 'via Diogenes Laertius' },
    { text: 'Education is the kindling of a flame, not the filling of a vessel.', source: 'Attributed (via Plutarch)' },
    { text: 'He is richest who is content with the least.', source: 'Attributed (via Diogenes Laertius)' },
    { text: 'Let him who would move the world first move himself.', source: 'Attributed' },
    { text: 'Wonder is the beginning of wisdom.', source: 'Attributed (via Plato, Theaetetus)' },
    { text: 'True wisdom comes to each of us when we realize how little we understand about life.', source: 'via Plato, Apology' },
  ],

  // ─── New Philosophers (Sprint 2 Expansion) ────────────────────────

  'Epictetus': [
    { text: 'It is not things that disturb us, but our judgments about things.', source: 'Enchiridion, Chapter 5' },
    { text: 'Make the best use of what is in your power, and take the rest as it happens.', source: 'Discourses, Book 1' },
    { text: 'No man is free who is not master of himself.', source: 'Discourses, Book 4' },
    { text: 'First say to yourself what you would be; and then do what you have to do.', source: 'Discourses, Book 3, Chapter 23' },
    { text: 'Wealth consists not in having great possessions, but in having few wants.', source: 'Discourses, Book 4' },
    { text: 'It is impossible for a man to learn what he thinks he already knows.', source: 'Discourses, Book 2, Chapter 17' },
    { text: 'If you want to improve, be content to be thought foolish and stupid.', source: 'Enchiridion, Chapter 13' },
    { text: 'Circumstances do not make the man, they reveal him.', source: 'Discourses, Book 1, Chapter 24' },
    { text: 'Only the educated are free.', source: 'Discourses, Book 2, Chapter 1' },
    { text: 'He who laughs at himself never runs out of things to laugh at.', source: 'Attributed, Discourses context' },
  ],
  'Cato the Younger': [
    { text: 'I would rather be right than be president.', source: 'Attributed (via Plutarch, Life of Cato the Younger)' },
    { text: 'The best way to keep good acts in memory is to refresh them with new.', source: 'Attributed (via Plutarch)' },
    { text: 'I begin to speak only when I am certain what I shall say is not better left unsaid.', source: 'Attributed (via Plutarch, Life of Cato)' },
    { text: 'An angry man opens his mouth and shuts his eyes.', source: 'Attributed (via Plutarch)' },
    { text: 'Bitter are the roots of study, but how sweet their fruit.', source: 'Attributed (via Diogenes Laertius)' },
    { text: 'I can pardon everybody\'s mistakes except my own.', source: 'Attributed (via Plutarch, Life of Cato)' },
    { text: 'In doing nothing, men learn to do evil.', source: 'Attributed (via Plutarch)' },
    { text: 'He who fears death either fears the loss of sensation or a different kind of sensation.', source: 'Attributed (via Plutarch)' },
    { text: 'Wise men profit more from fools than fools from wise men.', source: 'Attributed (via Plutarch, Life of Cato)' },
    { text: 'Those who are feared are hated, and those who are hated wish dead those they fear.', source: 'Attributed (via Cicero, De Officiis context)' },
  ],
  'Musonius Rufus': [
    { text: 'We begin to lose our hesitation to do immoral things when we lose our hesitation to speak of them.', source: 'Lectures, Fragment 1' },
    { text: 'If you accomplish something good with hard work, the labor passes quickly but the good endures.', source: 'Lectures, Fragment 51' },
    { text: 'Virtue is not simply theoretical knowledge, but it is practical application as well.', source: 'Lectures, On Training' },
    { text: 'Since every man dies, it is better to die with distinction than to live long.', source: 'Lectures, Fragment 38' },
    { text: 'In order to protect ourselves we must live like doctors and be continually treating ourselves with reason.', source: 'Lectures, On Food' },
    { text: 'How much more damage anger and grief do than the things that cause them.', source: 'Lectures, Fragment 36' },
    { text: 'You will earn the respect of all if you begin by earning the respect of yourself.', source: 'Lectures, Fragment 52' },
    { text: 'To relax the mind is to lose it.', source: 'Lectures, On Training' },
    { text: 'Could there be a more profitable practice than the study of how to live well?', source: 'Lectures, That Women Too Should Study Philosophy' },
    { text: 'Practice philosophy together, as you eat and drink together.', source: 'Lectures, On Marriage' },
  ],
  'Cleanthes': [
    { text: 'Lead me, O Zeus, and thou O Destiny, to wherever your decrees have fixed my lot.', source: 'Hymn to Zeus (via Epictetus, Enchiridion 53)' },
    { text: 'The willing are led by fate, the reluctant are dragged.', source: 'Attributed (via Seneca, Letters 107)' },
    { text: 'He has the most who is most content with the least.', source: 'Attributed (via Diogenes Laertius)' },
    { text: 'Fate guides the willing and drags along the unwilling.', source: 'Attributed (via Seneca, Letters 107)' },
    { text: 'The soul is dyed with the color of its leisure thoughts.', source: 'Attributed' },
    { text: 'Do not be disturbed at the approach of change.', source: 'Attributed (via Diogenes Laertius, Lives)' },
    { text: 'If good fortune comes your way, receive it temperately.', source: 'Attributed (via Diogenes Laertius)' },
    { text: 'Nothing great is achieved without effort.', source: 'Attributed (via Diogenes Laertius, Lives)' },
    { text: 'It is in adversity that virtue shines most brightly.', source: 'Attributed (via Stobaeus)' },
    { text: 'The wise man carries his possessions within him.', source: 'Attributed (via Diogenes Laertius)' },
  ],
  'Zeno of Citium': [
    { text: 'Man conquers the world by conquering himself.', source: 'Attributed (via Diogenes Laertius, Lives 7)' },
    { text: 'We have two ears and one mouth, so we should listen more than we say.', source: 'Attributed (via Diogenes Laertius)' },
    { text: 'Well-being is attained little by little, and is no little thing itself.', source: 'Attributed (via Diogenes Laertius, Lives 7)' },
    { text: 'The goal of life is living in agreement with nature.', source: 'Attributed (via Diogenes Laertius, Lives 7)' },
    { text: 'Happiness is a good flow of life.', source: 'Attributed (via Stobaeus)' },
    { text: 'No evil is honorable, but death is honorable; therefore death is not evil.', source: 'Attributed (via Diogenes Laertius)' },
    { text: 'Better to trip with the feet than with the tongue.', source: 'Attributed (via Diogenes Laertius, Lives 7)' },
    { text: 'The reason why we have two ears and only one mouth is so we might listen more and talk less.', source: 'Attributed (via Diogenes Laertius)' },
    { text: 'Extravagance is its own destroyer.', source: 'Attributed (via Stobaeus)' },
    { text: 'Nothing is more hostile to a firm grasp on knowledge than self-deception.', source: 'Attributed (via Cicero, Academica)' },
  ],
  'Chrysippus': [
    { text: 'The universe itself is God and the universal outpouring of its soul.', source: 'Attributed (via Cicero, De Natura Deorum 1.39)' },
    { text: 'Living virtuously is equal to living in accordance with experience of the actual course of nature.', source: 'Attributed (via Diogenes Laertius, Lives 7)' },
    { text: 'There could be no justice unless there were also injustice.', source: 'Attributed (via Aulus Gellius, Noctes Atticae)' },
    { text: 'Fate is the endless chain of causation, whereby things are.', source: 'Attributed (via Aulus Gellius)' },
    { text: 'The wise man is free from perturbation; not because he is insensible, but because he is master.', source: 'Attributed (via Diogenes Laertius, Lives 7)' },
    { text: 'We are members of one great body, planted by nature in a mutual love.', source: 'Attributed (via Seneca, Letters 95)' },
    { text: 'Passion is an irrational movement of the soul contrary to nature.', source: 'Attributed (via Diogenes Laertius, Lives 7)' },
    { text: 'What is rational is good; what is good is rational.', source: 'Attributed (via Diogenes Laertius)' },
    { text: 'The end of being is to act in conformity with nature.', source: 'Attributed (via Diogenes Laertius, Lives 7)' },
    { text: 'Not even Zeus can undo what has been done.', source: 'Attributed (via Diogenes Laertius)' },
  ],
  'Thich Nhat Hanh': [
    { text: 'The present moment is filled with joy and happiness. If you are attentive, you will see it.', source: 'Peace Is Every Step (1991)' },
    { text: 'Smile, breathe, and go slowly.', source: 'Being Peace (1987)' },
    { text: 'Because you are alive, everything is possible.', source: 'Living Buddha, Living Christ (1995)' },
    { text: 'Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.', source: 'Stepping into Freedom (1997)' },
    { text: 'When another person makes you suffer, it is because he suffers deeply within himself.', source: 'The Heart of the Buddha\'s Teaching (1998)' },
    { text: 'Walk as if you are kissing the Earth with your feet.', source: 'Peace Is Every Step (1991)' },
    { text: 'Sometimes your joy is the source of your smile, but sometimes your smile can be the source of your joy.', source: 'Being Peace (1987)' },
    { text: 'To be beautiful means to be yourself. You don\'t need to be accepted by others.', source: 'Being Peace (1987)' },
    { text: 'People have a hard time letting go of their suffering. They prefer suffering that is familiar.', source: 'The Heart of the Buddha\'s Teaching (1998)' },
    { text: 'Drink your tea slowly and reverently, as if it is the axis on which the world earth revolves.', source: 'The Miracle of Mindfulness (1975)' },
  ],
  'Rumi': [
    { text: 'The wound is the place where the Light enters you.', source: 'Collected works (13th century, trans. Coleman Barks)' },
    { text: 'What you seek is seeking you.', source: 'The Masnavi, Book 1 (13th century)' },
    { text: 'Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.', source: 'Collected works (trans. Coleman Barks)' },
    { text: 'Don\'t be satisfied with stories, how things have gone with others. Unfold your own myth.', source: 'The Masnavi (13th century, trans. Coleman Barks)' },
    { text: 'Silence is the language of God, all else is poor translation.', source: 'Collected works (13th century)' },
    { text: 'Let yourself be silently drawn by the strange pull of what you really love.', source: 'Collected works (trans. Coleman Barks)' },
    { text: 'You were born with wings, why prefer to crawl through life?', source: 'The Masnavi (13th century)' },
    { text: 'Raise your words, not voice. It is rain that grows flowers, not thunder.', source: 'Collected works (13th century)' },
    { text: 'The only lasting beauty is the beauty of the heart.', source: 'The Masnavi, Book 1 (13th century)' },
    { text: 'Out beyond ideas of wrongdoing and rightdoing, there is a field. I will meet you there.', source: 'Collected works (trans. Coleman Barks)' },
  ],
  'Confucius': [
    { text: 'It does not matter how slowly you go as long as you do not stop.', source: 'Attributed (Analects context)' },
    { text: 'Our greatest glory is not in never falling, but in rising every time we fall.', source: 'Attributed (via various translations)' },
    { text: 'Real knowledge is to know the extent of one\'s ignorance.', source: 'Analects, Book 2, Chapter 17' },
    { text: 'Before you embark on a journey of revenge, dig two graves.', source: 'Attributed' },
    { text: 'Everything has beauty, but not everyone sees it.', source: 'Attributed (Analects context)' },
    { text: 'The man who moves a mountain begins by carrying away small stones.', source: 'Attributed (Analects context)' },
    { text: 'He who knows all the answers has not been asked all the questions.', source: 'Attributed' },
    { text: 'When it is obvious that goals cannot be reached, don\'t adjust the goals, adjust the action steps.', source: 'Attributed (Analects context)' },
    { text: 'The funniest people are the saddest ones.', source: 'Attributed' },
    { text: 'To see what is right and not do it is the worst cowardice.', source: 'Analects, Book 2, Chapter 24' },
  ],
  'Zhuangzi': [
    { text: 'Happiness is the absence of the striving for happiness.', source: 'Zhuangzi, Chapter 18' },
    { text: 'Flow with whatever may happen and let your mind be free.', source: 'Zhuangzi, Chapter 4' },
    { text: 'The fish trap exists because of the fish; once you\'ve gotten the fish, you can forget the trap.', source: 'Zhuangzi, Chapter 26' },
    { text: 'We cling to our own point of view, as though everything depended on it.', source: 'Zhuangzi, Chapter 2' },
    { text: 'Rewards and punishments are the lowest form of education.', source: 'Zhuangzi, Chapter 14' },
    { text: 'When there is no more separation between this and that, it is called the still-point of the Tao.', source: 'Zhuangzi, Chapter 2' },
    { text: 'Great wisdom is generous; petty wisdom is contentious.', source: 'Zhuangzi, Chapter 2' },
    { text: 'Do not struggle. Go with the flow of things, and you will find yourself at one with the universe.', source: 'Zhuangzi, Chapter 7' },
    { text: 'Life comes from the earth and life returns to the earth.', source: 'Zhuangzi, Chapter 22' },
    { text: 'All things are one. What is beautiful is absolutely beautiful; what is ugly is absolutely ugly.', source: 'Zhuangzi, Chapter 2' },
  ],
  'D.T. Suzuki': [
    { text: 'The idea of self is a fiction created by the intellect.', source: 'An Introduction to Zen Buddhism (1934)' },
    { text: 'Before Zen, men are men and mountains are mountains.', source: 'Essays in Zen Buddhism, First Series (1927)' },
    { text: 'Unless it grows out of yourself no knowledge is really yours; it is only borrowed plumage.', source: 'An Introduction to Zen Buddhism (1934)' },
    { text: 'The truth of Zen is the truth of life, and life means to live, to move, to act.', source: 'An Introduction to Zen Buddhism (1934)' },
    { text: 'Zen is not a philosophy; it is poetry.', source: 'Zen and Japanese Culture (1959)' },
    { text: 'The more you suffer, the deeper grows your character, and with the deepening of your character you read the more penetratingly into the secrets of life.', source: 'An Introduction to Zen Buddhism (1934)' },
    { text: 'When my existence is at its lowest ebb, that is when the light from a deeper level shines most brightly.', source: 'Living by Zen (1950)' },
    { text: 'If you have heard of the Tao in the morning, it is all right to die in the evening.', source: 'Essays in Zen Buddhism, Third Series (1934)' },
    { text: 'Personal experience is everything in Zen.', source: 'An Introduction to Zen Buddhism (1934)' },
    { text: 'Zen opens a man\'s eyes to the greatest mystery as it is daily and hourly performed.', source: 'An Introduction to Zen Buddhism (1934)' },
  ],
  'Pema Chodron': [
    { text: 'You are the sky. Everything else is just the weather.', source: 'When Things Fall Apart (1997)' },
    { text: 'Nothing ever goes away until it teaches us what we need to know.', source: 'When Things Fall Apart (1997)' },
    { text: 'Lean into the sharp points and fully experience them.', source: 'When Things Fall Apart (1997)' },
    { text: 'The most fundamental aggression to ourselves is to remain ignorant by not having the courage to look at ourselves honestly.', source: 'When Things Fall Apart (1997)' },
    { text: 'Compassion is not a relationship between the healer and the wounded.', source: 'The Places That Scare You (2001)' },
    { text: 'We think that the point is to pass the test or overcome the problem, but the truth is that things don\'t really get solved.', source: 'When Things Fall Apart (1997)' },
    { text: 'Fear is a natural reaction to moving closer to the truth.', source: 'When Things Fall Apart (1997)' },
    { text: 'If we learn to open our hearts, anyone can be our teacher.', source: 'When Things Fall Apart (1997)' },
    { text: 'Letting there be room for not knowing is the most important thing of all.', source: 'When Things Fall Apart (1997)' },
    { text: 'To be fully alive, fully human, and completely awake is to be continually thrown out of the nest.', source: 'When Things Fall Apart (1997)' },
  ],
  'Carl Sagan': [
    { text: 'Somewhere, something incredible is waiting to be known.', source: 'Attributed (various interviews, 1970s)' },
    { text: 'For small creatures such as we, the vastness is bearable only through love.', source: 'Contact (1985)' },
    { text: 'We are a way for the universe to know itself.', source: 'Cosmos: A Personal Voyage (1980)' },
    { text: 'Extraordinary claims require extraordinary evidence.', source: 'Cosmos: A Personal Voyage (1980)' },
    { text: 'The nitrogen in our DNA, the calcium in our teeth, the iron in our blood were all made in collapsing stars.', source: 'Cosmos: A Personal Voyage (1980)' },
    { text: 'Look again at that dot. That\'s here. That\'s home. That\'s us.', source: 'Pale Blue Dot (1994)' },
    { text: 'Every one of us is, in the cosmic perspective, precious.', source: 'Cosmos: A Personal Voyage (1980)' },
    { text: 'Imagination will often carry us to worlds that never were. But without it we go nowhere.', source: 'Cosmos: A Personal Voyage (1980)' },
    { text: 'Science is not only compatible with spirituality; it is a profound source of spirituality.', source: 'The Demon-Haunted World (1996)' },
    { text: 'We are like butterflies who flutter for a day and think it is forever.', source: 'Cosmos: A Personal Voyage (1980)' },
  ],
  'Marie Curie': [
    { text: 'Nothing in life is to be feared, it is only to be understood.', source: 'Attributed (various biographies)' },
    { text: 'I am among those who think that science has great beauty.', source: 'Letter to her sister Bronislawa (1894)' },
    { text: 'Be less curious about people and more curious about ideas.', source: 'Attributed' },
    { text: 'Life is not easy for any of us. But what of that? We must have perseverance.', source: 'Lecture (1911)' },
    { text: 'One never notices what has been done; one can only see what remains to be done.', source: 'Letter to her brother (1894)' },
    { text: 'I was taught that the way of progress was neither swift nor easy.', source: 'Pierre Curie memoir (1923)' },
    { text: 'You cannot hope to build a better world without improving the individuals.', source: 'Pierre Curie memoir (1923)' },
    { text: 'All my mind was centered on my studies.', source: 'Autobiographical Notes (1923)' },
    { text: 'First principle: never to let oneself be beaten down by persons or by events.', source: 'Letter to her sister (1899)' },
    { text: 'There are sadistic scientists who hurry to hunt down errors instead of establishing the truth.', source: 'Attributed (lecture notes)' },
  ],
  'Nikola Tesla': [
    { text: 'If you want to find the secrets of the universe, think in terms of energy, frequency and vibration.', source: 'Attributed (various interviews)' },
    { text: 'The present is theirs; the future, for which I really worked, is mine.', source: 'Interview, New York Times (1931)' },
    { text: 'I don\'t care that they stole my idea. I care that they don\'t have any of their own.', source: 'Attributed' },
    { text: 'Our virtues and our failings are inseparable, like force and matter.', source: 'My Inventions (1919)' },
    { text: 'Be alone, that is the secret of invention; be alone, that is when ideas are born.', source: 'Attributed (various interviews)' },
    { text: 'The day science begins to study non-physical phenomena, it will make more progress in one decade than in all previous centuries.', source: 'Attributed' },
    { text: 'What one man calls God, another calls the laws of physics.', source: 'Attributed (various interviews)' },
    { text: 'Let the future tell the truth, and evaluate each one according to his work and accomplishments.', source: 'Interview (1927)' },
    { text: 'The spread of civilization may be likened to a fire; first, a feeble spark, next a flickering flame, then a mighty blaze.', source: 'My Inventions (1919)' },
    { text: 'Instinct is something which transcends knowledge.', source: 'My Inventions (1919)' },
  ],
  'Rachel Carson': [
    { text: 'Those who contemplate the beauty of the earth find reserves of strength that will endure as long as life lasts.', source: 'The Sense of Wonder (1965)' },
    { text: 'In every outthrust headland, in every curving beach, in every grain of sand there is the story of the earth.', source: 'The Edge of the Sea (1955)' },
    { text: 'The more clearly we can focus our attention on the wonders of the universe, the less taste we shall have for destruction.', source: 'Silent Spring (1962)' },
    { text: 'Those who dwell among the beauties and mysteries of the earth are never alone or weary of life.', source: 'The Sense of Wonder (1965)' },
    { text: 'In nature nothing exists alone.', source: 'Silent Spring (1962)' },
    { text: 'If a child is to keep alive his inborn sense of wonder, he needs the companionship of at least one adult who can share it.', source: 'The Sense of Wonder (1965)' },
    { text: 'One way to open your eyes is to ask yourself, "What if I had never seen this before?"', source: 'The Sense of Wonder (1965)' },
    { text: 'The human race is challenged more than ever before to demonstrate our mastery, not over nature but of ourselves.', source: 'Silent Spring (1962)' },
    { text: 'It is a wholesome and necessary thing for us to turn again to the earth.', source: 'The Sense of Wonder (1965)' },
    { text: 'The sea, once it casts its spell, holds one in its net of wonder forever.', source: 'The Sea Around Us (1951)' },
  ],
  'Neil deGrasse Tyson': [
    { text: 'The universe is under no obligation to make sense to you.', source: 'Astrophysics for People in a Hurry (2017)' },
    { text: 'The good thing about science is that it\'s true whether or not you believe in it.', source: 'Real Time with Bill Maher (2011)' },
    { text: 'We are all connected; to each other, biologically. To the earth, chemically. To the universe, atomically.', source: 'Attributed (various talks)' },
    { text: 'We are part of this universe; we are in this universe, but perhaps more important, the universe is in us.', source: 'TIME 100 Gala (2012)' },
    { text: 'Curious that we spend more time congratulating people who have succeeded than encouraging people who have not.', source: 'Astrophysics for People in a Hurry (2017)' },
    { text: 'The atoms of our bodies are traceable to stars that manufactured them and exploded their enriched guts.', source: 'Astrophysics for People in a Hurry (2017)' },
    { text: 'Knowing how to think empowers you far beyond those who know only what to think.', source: 'Attributed (various talks)' },
    { text: 'There is no shame in not knowing. The problem arises when irrational thought and attendant behavior fill the vacuum left by ignorance.', source: 'The Sky Is Not the Limit (2000)' },
    { text: 'For me, I am driven by two main philosophies: know more today about the world than I knew yesterday.', source: 'Attributed (various interviews)' },
    { text: 'The universe is big, but we are not small. We are big because we comprehend the universe.', source: 'Attributed (various talks)' },
  ],
  'Ada Lovelace': [
    { text: 'The Analytical Engine weaves algebraic patterns just as the Jacquard loom weaves flowers and leaves.', source: 'Notes on Menabrea\'s Sketch of the Analytical Engine (1843)' },
    { text: 'Imagination is the discovering faculty, pre-eminently.', source: 'Letter to Charles Babbage (1843)' },
    { text: 'I am more than ever now the bride of science.', source: 'Letter to her mother (1834)' },
    { text: 'The science of operations is a science of itself, and has its own abstract truth and value.', source: 'Notes on Menabrea\'s Sketch (1843)' },
    { text: 'That brain of mine is something more than merely mortal, as time will show.', source: 'Letter to her mother (1844)' },
    { text: 'Mathematical science shows what is. It is the language of unseen relations between things.', source: 'Notes on Menabrea\'s Sketch (1843)' },
    { text: 'I never am really satisfied that I understand anything; because, understand it well as I may, I still feel I have not understood it.', source: 'Letter to Augustus De Morgan (1843)' },
    { text: 'Religion to me is science and science is religion.', source: 'Letter to her mother (1838)' },
    { text: 'I can throw rays from every quarter of the universe into one vast focus.', source: 'Letter to Charles Babbage (1843)' },
    { text: 'The intellectual, the moral, the religious seem to me all naturally bound up and interlinked together in one great framework.', source: 'Letter to her mother (1841)' },
  ],
  'Werner Heisenberg': [
    { text: 'What we observe is not nature itself, but nature exposed to our method of questioning.', source: 'Physics and Philosophy (1958)' },
    { text: 'The first gulp from the glass of natural sciences will turn you into an atheist, but at the bottom God is waiting.', source: 'Attributed (various lectures)' },
    { text: 'Not only is the universe stranger than we think, it is stranger than we can think.', source: 'Across the Frontiers (1974)' },
    { text: 'An expert is someone who knows some of the worst mistakes that can be made in his subject.', source: 'Physics and Beyond (1971)' },
    { text: 'Every experiment destroys some of the knowledge of the system which was obtained by previous experiments.', source: 'The Physical Principles of the Quantum Theory (1930)' },
    { text: 'In the strict formulation of the law of causality, it is not the future that is determined by the present but the opposite.', source: 'Physics and Philosophy (1958)' },
    { text: 'Natural science does not simply describe and explain nature; it describes nature as exposed to our method of questioning.', source: 'Physics and Philosophy (1958)' },
    { text: 'The problems of language here are really serious.', source: 'Physics and Philosophy (1958)' },
    { text: 'Even for the physicist the description in plain language will be a criterion of the degree of understanding.', source: 'Physics and Philosophy (1958)' },
    { text: 'Quantum theory provides us with an illustration of the fact that we can fully understand a connection though we can only speak of it in images and parables.', source: 'Physics and Beyond (1971)' },
  ],
  'Ralph Waldo Emerson': [
    { text: 'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.', source: 'Self-Reliance (1841)' },
    { text: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', source: 'Attributed (essays context)' },
    { text: 'The only person you are destined to become is the person you decide to be.', source: 'Self-Reliance (1841)' },
    { text: 'Do not go where the path may lead, go instead where there is no path and leave a trail.', source: 'Self-Reliance (1841)' },
    { text: 'For every minute you are angry you lose sixty seconds of happiness.', source: 'Journals (1842)' },
    { text: 'Life is a journey, not a destination.', source: 'Self-Reliance (1841)' },
    { text: 'The earth laughs in flowers.', source: 'Hamatreya (poem, 1847)' },
    { text: 'Once you make a decision, the universe conspires to make it happen.', source: 'Attributed (various essays)' },
    { text: 'Nothing great was ever achieved without enthusiasm.', source: 'Circles (1841)' },
    { text: 'Write it on your heart that every day is the best day in the year.', source: 'Society and Solitude (1870)' },
  ],
  'Kahlil Gibran': [
    { text: 'Your pain is the breaking of the shell that encloses your understanding.', source: 'The Prophet (1923)' },
    { text: 'Out of suffering have emerged the strongest souls; the most massive characters are seared with scars.', source: 'The Prophet (1923)' },
    { text: 'You talk when you cease to be at peace with your thoughts.', source: 'The Prophet (1923)' },
    { text: 'Your children are not your children. They are the sons and daughters of Life\'s longing for itself.', source: 'The Prophet (1923)' },
    { text: 'The deeper that sorrow carves into your being, the more joy you can contain.', source: 'The Prophet (1923)' },
    { text: 'And ever has it been known that love knows not its own depth until the hour of separation.', source: 'The Prophet (1923)' },
    { text: 'Trees are poems the earth writes upon the sky.', source: 'Sand and Foam (1926)' },
    { text: 'Keep me away from the wisdom which does not cry, the philosophy which does not laugh.', source: 'Sand and Foam (1926)' },
    { text: 'If you love somebody, let them go, for if they return, they were always yours.', source: 'Attributed (The Prophet context)' },
    { text: 'Generosity is giving more than you can, and pride is taking less than you need.', source: 'Sand and Foam (1926)' },
  ],
  'Mary Oliver': [
    { text: 'Tell me, what is it you plan to do with your one wild and precious life?', source: 'The Summer Day (poem, 1990)' },
    { text: 'Someone I loved once gave me a box full of darkness. It took me years to understand that this too, was a gift.', source: 'Thirst (2006)' },
    { text: 'Instructions for living a life: Pay attention. Be astonished. Tell about it.', source: 'Sometimes (poem, 2006)' },
    { text: 'You do not have to be good. You do not have to walk on your knees for a hundred miles through the desert, repenting.', source: 'Wild Geese (poem, 1986)' },
    { text: 'Keep some room in your heart for the unimaginable.', source: 'Evidence (2009)' },
    { text: 'I don\'t want to end up simply having visited this world.', source: 'When Death Comes (poem, 1992)' },
    { text: 'The most regretful people on earth are those who felt the call to creative work, who felt their own creative power, and gave up.', source: 'Upstream (2016)' },
    { text: 'Attention is the beginning of devotion.', source: 'Upstream (2016)' },
    { text: 'To pay attention, this is our endless and proper work.', source: 'Yes! No! (poem, 2006)' },
    { text: 'I found I was neither combative nor ready to surrender.', source: 'A Thousand Mornings (2012)' },
  ],
  'Oscar Wilde': [
    { text: 'Be yourself; everyone else is already taken.', source: 'Attributed' },
    { text: 'To live is the rarest thing in the world. Most people exist, that is all.', source: 'The Soul of Man Under Socialism (1891)' },
    { text: 'We are all in the gutter, but some of us are looking at the stars.', source: 'Lady Windermere\'s Fan (1892)' },
    { text: 'The truth is rarely pure and never simple.', source: 'The Importance of Being Earnest (1895)' },
    { text: 'Experience is merely the name men gave to their mistakes.', source: 'The Picture of Dorian Gray (1890)' },
    { text: 'A man who does not think for himself does not think at all.', source: 'The Soul of Man Under Socialism (1891)' },
    { text: 'With freedom, books, flowers, and the moon, who could not be happy?', source: 'De Profundis (1905)' },
    { text: 'Always forgive your enemies; nothing annoys them so much.', source: 'Attributed' },
    { text: 'Every saint has a past, and every sinner has a future.', source: 'A Woman of No Importance (1893)' },
    { text: 'I have the simplest tastes. I am always satisfied with the best.', source: 'Attributed' },
  ],
  'Henry David Thoreau': [
    { text: 'Go confidently in the direction of your dreams. Live the life you have imagined.', source: 'Walden (1854)' },
    { text: 'Not until we are lost do we begin to find ourselves.', source: 'Walden (1854)' },
    { text: 'It\'s not what you look at that matters, it\'s what you see.', source: 'Journal (August 5, 1851)' },
    { text: 'The mass of men lead lives of quiet desperation.', source: 'Walden (1854)' },
    { text: 'Happiness is like a butterfly: the more you chase it, the more it will elude you.', source: 'Attributed (Journal context)' },
    { text: 'I went to the woods because I wished to live deliberately.', source: 'Walden (1854)' },
    { text: 'An early morning walk is a blessing for the whole day.', source: 'Journal (April 20, 1840)' },
    { text: 'Our life is frittered away by detail. Simplify, simplify.', source: 'Walden (1854)' },
    { text: 'Things do not change; we change.', source: 'Walden (1854)' },
    { text: 'As if you could kill time without injuring eternity.', source: 'Walden (1854)' },
  ],
  'Maya Angelou': [
    { text: 'We delight in the beauty of the butterfly, but rarely admit the changes it has gone through.', source: 'Attributed (various interviews)' },
    { text: 'If you don\'t like something, change it. If you can\'t change it, change your attitude.', source: 'Wouldn\'t Take Nothing for My Journey Now (1993)' },
    { text: 'There is no greater agony than bearing an untold story inside you.', source: 'I Know Why the Caged Bird Sings (1969)' },
    { text: 'I\'ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.', source: 'Attributed (various speeches)' },
    { text: 'We all should know that diversity makes for a rich tapestry.', source: 'Wouldn\'t Take Nothing for My Journey Now (1993)' },
    { text: 'Courage is the most important of all the virtues because without courage, you can\'t practice any other virtue consistently.', source: 'Interview (2013)' },
    { text: 'Try to be a rainbow in someone\'s cloud.', source: 'Letter to My Daughter (2008)' },
    { text: 'When you know better you do better.', source: 'Attributed (Oprah Winfrey Show, 1990s)' },
    { text: 'Life is not measured by the number of breaths we take, but by the moments that take our breath away.', source: 'Attributed' },
    { text: 'You alone are enough. You have nothing to prove to anybody.', source: 'Attributed (various interviews)' },
  ],
  'Walt Whitman': [
    { text: 'I am large, I contain multitudes.', source: 'Song of Myself (Leaves of Grass, 1855)' },
    { text: 'Keep your face always toward the sunshine — and shadows will fall behind you.', source: 'Attributed (Leaves of Grass context)' },
    { text: 'Do I contradict myself? Very well then, I contradict myself.', source: 'Song of Myself (Leaves of Grass, 1855)' },
    { text: 'Not I, nor anyone else can travel that road for you. You must travel it by yourself.', source: 'Song of Myself (Leaves of Grass, 1855)' },
    { text: 'Re-examine all that you have been told. Dismiss that which insults your soul.', source: 'Preface to Leaves of Grass (1855)' },
    { text: 'Either define the moment or the moment will define you.', source: 'Attributed' },
    { text: 'I exist as I am, that is enough.', source: 'Song of Myself (Leaves of Grass, 1855)' },
    { text: 'The powerful play goes on, and you may contribute a verse.', source: 'O Me! O Life! (Leaves of Grass, 1867)' },
    { text: 'Henceforth I ask not good-fortune, I myself am good-fortune.', source: 'Song of the Open Road (1856)' },
    { text: 'To me, every hour of the day and night is an unspeakably perfect miracle.', source: 'Leaves of Grass (1855)' },
  ],
  'Hermann Hesse': [
    { text: 'Within you there is a stillness and a sanctuary to which you can retreat at any time.', source: 'Siddhartha (1922)' },
    { text: 'Some of us think holding on makes us strong, but sometimes it is letting go.', source: 'Siddhartha (1922)' },
    { text: 'The bird fights its way out of the egg. The egg is the world.', source: 'Demian (1919)' },
    { text: 'You know quite well, deep within you, that there is only a single magic, a single power, a single salvation: and that is called loving.', source: 'Narcissus and Goldmund (1930)' },
    { text: 'I have been and still am a seeker, but I have ceased to question stars and books; I have begun to listen to the teaching my blood whispers to me.', source: 'Demian (1919)' },
    { text: 'Wisdom cannot be imparted. Wisdom that a wise man attempts to impart always sounds like foolishness.', source: 'Siddhartha (1922)' },
    { text: 'Every man is more than just himself; he also represents the unique, the very special point at which the world\'s phenomena intersect.', source: 'Demian (1919)' },
    { text: 'Happiness is a how, not a what.', source: 'Attributed (Siddhartha context)' },
    { text: 'One never reaches home, but wherever friendly paths intersect, the whole world looks like home for a time.', source: 'Demian (1919)' },
    { text: 'What could I say to you that would be of value, except that perhaps you seek too much?', source: 'Siddhartha (1922)' },
  ],
  'Eckhart Tolle': [
    { text: 'Realize deeply that the present moment is all you ever have.', source: 'The Power of Now (1997)' },
    { text: 'Life is the dancer and you are the dance.', source: 'A New Earth (2005)' },
    { text: 'Acknowledging the good that you already have in your life is the foundation for all abundance.', source: 'A New Earth (2005)' },
    { text: 'The primary cause of unhappiness is never the situation but your thoughts about it.', source: 'A New Earth (2005)' },
    { text: 'Whatever the present moment contains, accept it as if you had chosen it.', source: 'The Power of Now (1997)' },
    { text: 'You can only lose something that you have, but you cannot lose something that you are.', source: 'A New Earth (2005)' },
    { text: 'Life will give you whatever experience is most helpful for the evolution of your consciousness.', source: 'A New Earth (2005)' },
    { text: 'Where there is anger, there is always pain underneath.', source: 'The Power of Now (1997)' },
    { text: 'It is not uncommon for people to spend their whole life waiting to start living.', source: 'The Power of Now (1997)' },
    { text: 'What a liberation to realize that the voice in my head is not who I am.', source: 'A New Earth (2005)' },
  ],
  'Ram Dass': [
    { text: 'The quieter you become, the more you can hear.', source: 'Be Here Now (1971)' },
    { text: 'We are all just walking each other home.', source: 'Attributed (various talks, 1970s)' },
    { text: 'The next message you need is always right where you are.', source: 'Be Here Now (1971)' },
    { text: 'Suffering is part of our training program for becoming wise.', source: 'Still Here (2000)' },
    { text: 'As long as you have certain desires about how it ought to be you can\'t see how it is.', source: 'Be Here Now (1971)' },
    { text: 'Treat everyone you meet like God in drag.', source: 'Attributed (various talks)' },
    { text: 'I would like my life to be a statement of love and compassion.', source: 'Attributed (various talks)' },
    { text: 'Start from where you are — not where you wish you were.', source: 'Attributed (various lectures)' },
    { text: 'In most of our human relationships, we spend much of our time reassuring one another that our costumes of identity are on straight.', source: 'Be Here Now (1971)' },
    { text: 'What you meet in another being is the projection of your own level of evolution.', source: 'Be Here Now (1971)' },
  ],
  'Deepak Chopra': [
    { text: 'Every time you are tempted to react in the same old way, ask if you want to be a prisoner of the past or a pioneer of the future.', source: 'The Seven Spiritual Laws of Success (1994)' },
    { text: 'In the midst of movement and chaos, keep stillness inside of you.', source: 'The Seven Spiritual Laws of Success (1994)' },
    { text: 'Nothing is more important than reconnecting with your bliss.', source: 'The Seven Spiritual Laws of Success (1994)' },
    { text: 'You must find the place inside yourself where nothing is impossible.', source: 'Attributed (various talks)' },
    { text: 'The highest levels of performance come to people who are centered, intuitive, creative, and reflective.', source: 'The Seven Spiritual Laws of Success (1994)' },
    { text: 'Happiness is a continuation of happenings which are not resisted.', source: 'Attributed (various talks)' },
    { text: 'If you want to reach a state of bliss, make a decision to relinquish the need to control.', source: 'The Seven Spiritual Laws of Success (1994)' },
    { text: 'The way you think, the way you behave, the way you eat, can influence your life by 30 to 50 years.', source: 'Ageless Body, Timeless Mind (1993)' },
    { text: 'The less you open your heart to others, the more your heart suffers.', source: 'The Path to Love (1997)' },
    { text: 'All great changes are preceded by chaos.', source: 'Attributed (various talks)' },
  ],
  'Paramahansa Yogananda': [
    { text: 'Live quietly in the moment and see the beauty of all before you.', source: 'Autobiography of a Yogi (1946)' },
    { text: 'The season of failure is the best time for sowing the seeds of success.', source: 'Autobiography of a Yogi (1946)' },
    { text: 'Kindness is the light that dissolves all walls between souls.', source: 'Where There Is Light (1988, posthumous)' },
    { text: 'You must not let your life run in the ordinary way; do something that nobody else has done.', source: 'Autobiography of a Yogi (1946)' },
    { text: 'There is a magnet in your heart that will attract true friends.', source: 'Where There Is Light (1988)' },
    { text: 'The power of unfulfilled desires is the root of all man\'s slavery.', source: 'Autobiography of a Yogi (1946)' },
    { text: 'Read a little. Meditate more. Think of God all the time.', source: 'Attributed (Self-Realization Fellowship talks)' },
    { text: 'Be as simple as you can be; you will be astonished to see how uncomplicated and happy your life can become.', source: 'Where There Is Light (1988)' },
    { text: 'Remain calm, serene, always in command of yourself. You will then find out how easy it is to get along.', source: 'Autobiography of a Yogi (1946)' },
    { text: 'Making others happy, through kindness of speech and sincerity of right advice, is a sign of true greatness.', source: 'Where There Is Light (1988)' },
  ],
  'Mooji': [
    { text: 'You are not the mind. If you know you are not the mind, then what difference does it make what it thinks?', source: 'White Fire (2014)' },
    { text: 'Step into the fire of self-discovery. This fire will not burn you, it will only burn what you are not.', source: 'Vaster Than Sky, Greater Than Space (2016)' },
    { text: 'Feelings are just visitors, let them come and go.', source: 'Attributed (satsang talks)' },
    { text: 'Don\'t be too quick to interpret the moment. Just keep quiet. My encouragement would always be: never think you know.', source: 'White Fire (2014)' },
    { text: 'The mind is like a wild horse. It will throw you off if you don\'t know how to ride it.', source: 'Attributed (satsang talks)' },
    { text: 'When the mind is quiet, it reflects reality as it is.', source: 'Vaster Than Sky, Greater Than Space (2016)' },
    { text: 'You are the unchanging awareness in which all activity takes place.', source: 'White Fire (2014)' },
    { text: 'Every thought, every emotion is only a visitor. You are the house.', source: 'Attributed (satsang talks)' },
    { text: 'If you take yourself to be the body and mind only, you will die. But when you discover yourself as awareness, you come to know you are immortal.', source: 'White Fire (2014)' },
    { text: 'The greatest step towards a life of simplicity is to learn to let go.', source: 'Vaster Than Sky, Greater Than Space (2016)' },
  ],
  'Sadhguru': [
    { text: 'The sign of intelligence is that you are constantly wondering.', source: 'Inner Engineering (2016)' },
    { text: 'If you resist change, you resist life.', source: 'Inner Engineering (2016)' },
    { text: 'The most beautiful moments in life are moments when you are expressing your joy, not when you are seeking it.', source: 'Inner Engineering (2016)' },
    { text: 'Your thoughts and emotions may keep you from living the life you want.', source: 'Inner Engineering (2016)' },
    { text: 'The quality of your life depends on how well you manage your body, your mind, your emotion, and your energies.', source: 'Inner Engineering (2016)' },
    { text: 'If you think you are big, you become small. If you know you are nothing, you become unlimited.', source: 'Mystic\'s Musings (2003)' },
    { text: 'People try to create an outwardly perfect life, but the quality of life is based on the inward.', source: 'Inner Engineering (2016)' },
    { text: 'Too many people are hungry not because there is a dearth of food. It is because there is a dearth of love and care.', source: 'Attributed (various talks)' },
    { text: 'When you do not know what to do, just be still. Stillness speaks.', source: 'Inner Engineering (2016)' },
    { text: 'Being spiritual means you have no boundaries for your experience.', source: 'Mystic\'s Musings (2003)' },
  ],
  'Wayne Dyer': [
    { text: 'When you change the way you look at things, the things you look at change.', source: 'The Power of Intention (2004)' },
    { text: 'You cannot always control what goes on outside. But you can always control what goes on inside.', source: 'Your Erroneous Zones (1976)' },
    { text: 'If you change the way you look at things, the things you look at change.', source: 'The Power of Intention (2004)' },
    { text: 'How people treat you is their karma; how you react is yours.', source: 'Your Erroneous Zones (1976)' },
    { text: 'You\'ll see it when you believe it.', source: 'You\'ll See It When You Believe It (1989)' },
    { text: 'Abundance is not something we acquire. It is something we tune into.', source: 'The Power of Intention (2004)' },
    { text: 'Don\'t die with your music still in you.', source: 'Wishes Fulfilled (2012)' },
    { text: 'Peace is the result of retraining your mind to process life as it is, rather than as you think it should be.', source: 'Your Erroneous Zones (1976)' },
    { text: 'With everything that has happened to you, you can either feel sorry for yourself or treat what has happened as a gift.', source: 'Your Erroneous Zones (1976)' },
    { text: 'Be miserable. Or motivate yourself. Whatever has to be done, it\'s always your choice.', source: 'Your Erroneous Zones (1976)' },
  ],
  'Simone de Beauvoir': [
    { text: 'One is not born, but rather becomes, a woman.', source: 'The Second Sex (1949)' },
    { text: 'I am too intelligent, too demanding, and too resourceful for anyone to be able to take charge of me entirely.', source: 'Memoirs of a Dutiful Daughter (1958)' },
    { text: 'Change your life today. Don\'t gamble on the future, act now, without delay.', source: 'Attributed (various writings)' },
    { text: 'One\'s life has value so long as one attributes value to the life of others.', source: 'The Coming of Age (1970)' },
    { text: 'To catch a husband is an art; to hold him is a job.', source: 'The Second Sex (1949)' },
    { text: 'I tore myself away from the safe comfort of certainties through my love for truth.', source: 'All Said and Done (1972)' },
    { text: 'Society cares about the individual only in so far as he is profitable.', source: 'The Coming of Age (1970)' },
    { text: 'Self-knowledge is no guarantee of happiness, but it is on the side of happiness.', source: 'The Prime of Life (1960)' },
    { text: 'You can\'t always control what happens to you, but you can control how you react to it.', source: 'Attributed (The Ethics of Ambiguity context)' },
    { text: 'In itself, homosexuality is as limiting as heterosexuality.', source: 'The Second Sex (1949)' },
  ],
  'Albert Camus': [
    { text: 'In the midst of winter, I found there was, within me, an invincible summer.', source: 'Return to Tipasa (1954)' },
    { text: 'Don\'t walk in front of me, I may not follow. Don\'t walk behind me, I may not lead. Walk beside me, just be my friend.', source: 'Attributed (various writings)' },
    { text: 'The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.', source: 'The Rebel (1951)' },
    { text: 'You will never be happy if you continue to search for what happiness consists of.', source: 'Attributed (Notebooks)' },
    { text: 'Man is the only creature who refuses to be what he is.', source: 'The Rebel (1951)' },
    { text: 'Real generosity toward the future lies in giving all to the present.', source: 'The Rebel (1951)' },
    { text: 'Should I kill myself, or have a cup of coffee?', source: 'The Myth of Sisyphus (1942)' },
    { text: 'The absurd does not liberate; it binds.', source: 'The Myth of Sisyphus (1942)' },
    { text: 'Live to the point of tears.', source: 'Notebooks 1935-1942 (posthumous)' },
    { text: 'One must imagine Sisyphus happy.', source: 'The Myth of Sisyphus (1942)' },
  ],
  'Viktor Frankl': [
    { text: 'When we are no longer able to change a situation, we are challenged to change ourselves.', source: 'Man\'s Search for Meaning (1946)' },
    { text: 'Everything can be taken from a man but one thing: the last of human freedoms — to choose one\'s attitude.', source: 'Man\'s Search for Meaning (1946)' },
    { text: 'Those who have a why to live can bear with almost any how.', source: 'Man\'s Search for Meaning (1946)' },
    { text: 'Between stimulus and response there is a space. In that space is our power to choose our response.', source: 'Attributed (Man\'s Search for Meaning context)' },
    { text: 'What is to give light must endure burning.', source: 'Man\'s Search for Meaning (1946)' },
    { text: 'An abnormal reaction to an abnormal situation is normal behavior.', source: 'Man\'s Search for Meaning (1946)' },
    { text: 'For the world is in a bad state, but everything will become still worse unless each of us does his best.', source: 'Man\'s Search for Meaning (1946)' },
    { text: 'Happiness cannot be pursued; it must ensue.', source: 'Man\'s Search for Meaning (1946)' },
    { text: 'Live as if you were living a second time, and as though you had acted wrongly the first time.', source: 'Man\'s Search for Meaning (1946)' },
    { text: 'No man should judge unless he asks himself in absolute honesty whether in a similar situation he might not have done the same.', source: 'Man\'s Search for Meaning (1946)' },
  ],
  'Hannah Arendt': [
    { text: 'The sad truth is that most evil is done by people who never make up their minds to be good or evil.', source: 'The Life of the Mind (1978)' },
    { text: 'Forgiveness is the key to action and freedom.', source: 'The Human Condition (1958)' },
    { text: 'The most radical revolutionary will become a conservative the day after the revolution.', source: 'Crises of the Republic (1972)' },
    { text: 'There are no dangerous thoughts; thinking itself is dangerous.', source: 'The Life of the Mind (1978)' },
    { text: 'Only crime and the criminal, it is true, confront us with the perplexity of radical evil.', source: 'The Origins of Totalitarianism (1951)' },
    { text: 'Power corresponds to the human ability not just to act but to act in concert.', source: 'On Violence (1970)' },
    { text: 'The trouble with lying and deceiving is that their efficiency depends entirely upon a clear notion of the truth.', source: 'Crises of the Republic (1972)' },
    { text: 'Under conditions of tyranny it is far easier to act than to think.', source: 'The Human Condition (1958)' },
    { text: 'Storytelling reveals meaning without committing the error of defining it.', source: 'Men in Dark Times (1968)' },
    { text: 'Education is the point at which we decide whether we love the world enough to assume responsibility for it.', source: 'Between Past and Future (1961)' },
  ],
  'Nassim Nicholas Taleb': [
    { text: 'Wind extinguishes a candle and energizes fire. You want to be the fire.', source: 'Antifragile (2012)' },
    { text: 'The three most harmful addictions are heroin, carbohydrates, and a monthly salary.', source: 'The Bed of Procrustes (2010)' },
    { text: 'If you see fraud and do not say fraud, you are a fraud.', source: 'Antifragile (2012)' },
    { text: 'The person you are most afraid to contradict is yourself.', source: 'The Bed of Procrustes (2010)' },
    { text: 'Difficulty is what wakes up the genius.', source: 'Antifragile (2012)' },
    { text: 'You are rich if and only if money you refuse tastes better than money you accept.', source: 'The Bed of Procrustes (2010)' },
    { text: 'Missing a train is only painful if you run after it.', source: 'The Black Swan (2007)' },
    { text: 'The robust is what does not need to be particularly sophisticated to work. Simple is robust.', source: 'Antifragile (2012)' },
    { text: 'Suckers try to win arguments, nonsuckers try to win.', source: 'The Bed of Procrustes (2010)' },
    { text: 'What matters isn\'t what a person has or doesn\'t have; it is what he or she is afraid of losing.', source: 'The Black Swan (2007)' },
  ],
  'Naval Ravikant': [
    { text: 'A fit body, a calm mind, a house full of love. These things cannot be bought — they must be earned.', source: 'Twitter / The Almanack of Naval Ravikant (2020)' },
    { text: 'Desire is a contract you make with yourself to be unhappy until you get what you want.', source: 'The Almanack of Naval Ravikant (2020)' },
    { text: 'The most important skill for getting rich is becoming a perpetual learner.', source: 'How to Get Rich podcast (2019)' },
    { text: 'If you can\'t see yourself working with someone for life, don\'t work with them for a day.', source: 'The Almanack of Naval Ravikant (2020)' },
    { text: 'All the real benefits in life come from compound interest.', source: 'The Almanack of Naval Ravikant (2020)' },
    { text: 'Happiness is the state when nothing is missing.', source: 'The Almanack of Naval Ravikant (2020)' },
    { text: 'Seek wealth, not money or status. Wealth is having assets that earn while you sleep.', source: 'Twitter / The Almanack of Naval Ravikant (2020)' },
    { text: 'The secret to public speaking is to speak as if you were talking to one person.', source: 'The Almanack of Naval Ravikant (2020)' },
    { text: 'A calm mind, a fit body, and a house full of love. These things cannot be bought.', source: 'Twitter (2018)' },
    { text: 'Play long-term games with long-term people.', source: 'How to Get Rich podcast (2019)' },
  ],
};

/**
 * Get a subset of verified quotes for a specific philosopher.
 * Returns 3-4 quotes for inclusion in the prompt so the model selects the most relevant one.
 *
 * @param philosopher - Name of the philosopher (must match a key in VERIFIED_QUOTES)
 * @param count - Number of quotes to return (default 4)
 * @returns Array of quote strings, or empty array if philosopher not found
 */
export function getQuotesForPrompt(philosopher: string, count: number = 4): string[] {
  const quotes = VERIFIED_QUOTES[philosopher];
  if (!quotes || quotes.length === 0) return [];

  // Use date-based rotation to vary which quotes are presented each day
  const dayNum = Math.floor(new Date().getTime() / (1000 * 60 * 60 * 24));
  const startIndex = dayNum % quotes.length;

  const selected: string[] = [];
  for (let i = 0; i < Math.min(count, quotes.length); i++) {
    const idx = (startIndex + i) % quotes.length;
    selected.push(quotes[idx].text);
  }

  return selected;
}

/**
 * Get all philosopher names that have verified quotes.
 */
export function getAvailablePhilosophers(): string[] {
  return Object.keys(VERIFIED_QUOTES);
}
